### ISSUE TITLE
[11:42:21 ERROR]: Could not pass event PlayerJoinEvent to ZonePracticeLite v3.04-SNAPSHOT

### ISSUE THREAD

**Issue by F3F5** [Nandi0813/ZonePractice-Lite#10]
[11:42:21 ERROR]: Could not pass event PlayerJoinEvent to ZonePracticeLite v3.04-SNAPSHOT
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:313) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:172) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:150) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:60) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:461) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:183) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1017) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: net.minecraft.server.v1_8_R3.ReportedException: Sending packet
at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:949) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:624) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at dev.nandi0813.practice.Manager.Inventory.SpawnInventory.SpawnInventory.setInventory(SpawnInventory.java:77) ~[?:?]
at dev.nandi0813.practice.Listener.PlayerJoin.onPlayerJoin(PlayerJoin.java:32) ~[?:?]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-126]
... 16 more
Caused by: java.lang.NullPointerException: type cannot be null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
at net.minecraft.server.v1_8_R3.NetworkManager.writePacket(NetworkManager.java:399) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:314) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.NetworkManager.dispatchPacket(NetworkManager.java:311) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:287) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:270) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:935) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:624) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at dev.nandi0813.practice.Manager.Inventory.SpawnInventory.SpawnInventory.setInventory(SpawnInventory.java:77) ~[?:?]
at dev.nandi0813.practice.Listener.PlayerJoin.onPlayerJoin(PlayerJoin.java:32) ~[?:?]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-126]
... 16 more
[11:42:21 WARN]: Failed to handle packet for /178.91.216.139:2031
java.lang.IllegalArgumentException: arraySize cannot be negative but was: -1
at com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at com.google.common.collect.Lists.computeArrayListCapacity(Lists.java:119) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at com.google.common.collect.Lists.newArrayListWithExpectedSize(Lists.java:208) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:329) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:172) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:150) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:60) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:461) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:183) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1017) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-126]
at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by F3F5** [comment]
ProtocolLib 5.2.0 issues?
