### ISSUE TITLE
ClassCastException 

### ISSUE THREAD

**Issue by F3F5** [Nandi0813/ZonePractice-Lite#4]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_8_R3.entity.CraftHorse cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_8_R3.entity.CraftHorse and org.bukkit.entity.Player are in unnamed module of loader 'app')
at dev.nandi0813.practice.Manager.Match.MatchListener.onRegen(MatchListener.java:322) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-121]
... 19 more

**Comment by F3F5** [comment]
https://github.com/Nandi0813/ZonePractice-Lite/pull/5
