### ISSUE TITLE
Plugin ZonePracticeLite v3.04-SNAPSHOT generated an exception while executing task 372016

### ISSUE THREAD

**Issue by F3F5** [Nandi0813/ZonePractice-Lite#9]
[11:52:02 WARN]: Exception in thread "Craft Scheduler Thread - 57"
[11:52:02 WARN]: org.apache.commons.lang.UnhandledException: Plugin ZonePracticeLite v3.04-SNAPSHOT generated an exception while executing task 372016
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "org.yaml.snakeyaml.nodes.Node.getNodeId()" because "node" is null
at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:120)
at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108)
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
at dev.nandi0813.practice.Manager.Profile.ProfileFile.saveFile(ProfileFile.java:183)
at dev.nandi0813.practice.Manager.Profile.ProfileFile.setProfileData(ProfileFile.java:84)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more

**Comment by F3F5** [comment]
ProtocolLib 5.2.0 issues?
